### ISSUE TITLE
Keyboard name and icon

### ISSUE THREAD

**Issue by Lastofthefirst** [ElishaAz/Sayboard#1]
Hey, sorry I got pulled to other things, but thanks again! And yes sorry I couldn't make an issue here directly at first as the option was not available, maybe it was off in settings.

Maybe for an app name you could, go with the idea of speech and birds singing/parroting, so it could be. The idea of parrot could be more thematically fitting because the keyboard will parrot what you say in text, right as you say it:

* warble
* warbleboard
* parrot
* parrotboard

Here could be some possible associated logos or app icons. I generated them with stable diffusion so they are fine to use license wise. Also when you are able to publish a new apk Im eager to try what you'v got. 😁

![warble](https://user-images.githubusercontent.com/47003973/194207888-fa202b32-c917-4114-b249-4a707d7495c9.jpg)
![warble2](https://user-images.githubusercontent.com/47003973/194207891-6570e596-2baf-4ecb-bc36-750cadb165d6.jpg)
![warble3](https://user-images.githubusercontent.com/47003973/194207893-3d425815-7ce0-4117-afdf-421793f7a0dc.jpg)
![warble4](https://user-images.githubusercontent.com/47003973/194207895-1f4123c3-3a0b-4e6a-827f-ab25c19fb56a.jpg)
![warble5](https://user-images.githubusercontent.com/47003973/194207896-bd7988e5-ae59-4b52-a982-58962bbaa77b.jpg)
![warble6](https://user-images.githubusercontent.com/47003973/194207897-6211ea0e-5067-4029-afd0-8b3d9d65c749.jpg)
![warble7](https://user-images.githubusercontent.com/47003973/194207898-71f8dc3f-b115-4c64-9352-facb01fdc91f.jpg)
![warble8](https://user-images.githubusercontent.com/47003973/194207899-f93b52a7-8042-4996-9b56-0265080a0a67.jpg)
![warble9](https://user-images.githubusercontent.com/47003973/194207900-068a2b8c-4cd1-44d9-bce6-1f33ba3d1d1e.jpg)
![warble10](https://user-images.githubusercontent.com/47003973/194207902-c10e532c-7f86-4f24-b18e-843e7069bfe8.jpg)
![warble11](https://user-images.githubusercontent.com/47003973/194207903-ca030f58-e0ac-4ff1-8930-225a925cf365.jpg)
![warble12](https://user-images.githubusercontent.com/47003973/194207905-b7fe20d9-40a3-4d19-98ca-142f123a82d0.jpg)
![warble13](https://user-images.githubusercontent.com/47003973/194207906-a0689614-101d-490f-94d3-c46e9223ed4b.jpg)
![warble14](https://user-images.githubusercontent.com/47003973/194209652-72567b23-9a06-4236-b8e5-48935e6d4270.jpg)
![warble15](https://user-images.githubusercontent.com/47003973/194209656-ae53001e-a86f-48e3-9916-bdea75cbe8dc.jpg)

**Comment by ElishaAz** [comment]
Sorry, I assumed Github will notify me when an issue is opened. It seems that's not the case by default.

I haven't seen your comment until after I published the new release, with the name `Sayboard`.
Your designes are quite good though.
