### ISSUE TITLE
SUGGESTION: skip the "Ready" and listen immediately instead

### ISSUE THREAD

**Issue by WAZAAAAA0** [ElishaAz/Sayboard#12]
current steps go like this:
1. (switch to Sayboard IME)
2. "Preparing the recognizer"
3. "Ready"
4. (tap)
5. "Say something"

suggested change:
1. (switch to Sayboard IME)
2. "Preparing the recognizer"
3. "Say something"

Skipping those would save time when first invoked and make it easier to use. But the ability to stop listening by tapping should stay.

**Comment by ElishaAz** [comment]
👍 it's on my to-do list.
