### ISSUE TITLE
when usinf as system app,not download working

### ISSUE THREAD

**Issue by LeOS-GSI** [ElishaAz/Sayboard#15]
Hi, I have added the apk to prebuilds in my LeOS-GSI. Now it is a system app. But I can't download any language. I think the issue is, that the app don't ask for storage permission.

**Comment by ElishaAz** [comment]
The most recent release uses internal app storage, and master uses private external data. Both of which do not require any permissions, see https://developer.android.com/training/data-storage/app-specific .

Please share the app version (or commit id if built from source), and logcat.

**Comment by LeOS-GSI** [comment]
Sorry, my fault. I have rebuild the GSI and now it's working fine.
