### ISSUE TITLE
Avoid spaces between words in Japanese and Chinese

### ISSUE THREAD

**Issue by moonbeamcelery** [ElishaAz/Sayboard#16]
Thank you for the development efforts! The app runs rather well for these languages, but neither of them adds spaces between words. It would be great if the keyboard skips adding spaces for these languages.

**Comment by ElishaAz** [comment]
I'll add it to my to-do list.

**Comment by dsssok** [comment]
> 感謝您的開發努力！該應用程序在這些語言上運行得相當好，但它們都沒有在單詞之間添加空格。如果鍵盤跳過為這些語言添加空格，那就太好了。

In Chinese input, there should be no space between words or characters, and each sentence should end with a punctuation mark such as a comma, period, question mark, or exclamation mark. You do not need to add punctuation marks, as we will manually add appropriate ones, but there should be no spaces!

中文字体输入(字与字)之间是不能有空格的，一句话完成后会有(标点符号，例: ， 。 ？ ！这4个是最常用的)，当然你不用加标点符号，因为我们会手动加上合适的符号。但不能有空格！

**Comment by sxr1223** [comment]
This bug seems to have reappeared in the latest version. Could you please take a look at this bug?
