### ISSUE TITLE
ACKNOWLEDGMENT - SAYBOARD is The First FOSS IME that I am aware of.

### ISSUE THREAD

**Issue by lpstandardrp** [ElishaAz/Sayboard#17]
ACKNOWLEDGMENT - SAYBOARD is The First FOSS IME that I am aware of.

 i am sick as a dog laying in bed i haven't been able to 'speech to text' in years (on Android, no offline Local privacy-friendly options) and in my experience, seeing the helpfulness that is Sayboard this morning, i want to bring to your attention my appreciation— and presumably and very confidently, on behalf of the many people that have similar experiences to myself in the utilization of the invaluable tool here you have made possible and accessible two a person and person's like myself, thank you t f t f
Thank you.
A metric flux ton.
Sincerest n Warmest Regards, 
B

**Comment by ElishaAz** [comment]
You're welcome
