### ISSUE TITLE
F-droid release

### ISSUE THREAD

**Issue by ThatOneCalculator** [ElishaAz/Sayboard#2]
Putting this either on F-droid or IzzyOnDroid would definitely help with app discovery :)

**Comment by Tombstone2K** [comment]
Maybe even the Google Play Store

**Comment by ElishaAz** [comment]
I created an issue on IzzyOnDroid: https://gitlab.com/IzzyOnDroid/repo/-/issues/453

**Comment by ElishaAz** [comment]
> The software should use its own unique Android “Application ID” based on a domain name under the developer’s control. For example, if the app is in a group called “foo” on gitlab.com, then the domain name could be io.gitlab.foo. It should not be based on someone’s domain name, (e.g. com.google.foo). Maven Central OSSRH provides good guidance.

The main reason I didn't do so yet is because I do not own elishaazaria.com. If that's not a hard requirement, then go ahead

**Comment by ElishaAz** [comment]
I guess wec an just change the Id for the fdroid relase to io.github.elishaaz.sayboard

**Comment by ElishaAz** [comment]
> @ElishaAz Is the code GPL-3.0-only or GPL-3.0-or-later licensed? That is not clear from the license file alone... See https://f-droid.org/en/docs/Build_Metadata_Reference/#License

GPL-3.0-only

**Comment by alensiljak** [comment]
I found the app on F-Droid. Does it mean this is done or did I get it from Izzy's repo?

**Comment by ThatOneCalculator** [comment]
IzzyOnDroid. 

![Screenshot_20231024-162212.png](https://github.com/ElishaAz/Sayboard/assets/44733677/2a2857a5-fbaa-47cc-b0af-bfa68b602516)

**Comment by alensiljak** [comment]
Ah, that's right. One needs to tap on the version row to see that detail in the F-Droid client.

**Comment by ThatOneCalculator** [comment]
Unrelated, but you should give Droid-ify a try. It's a lot nicer than the default app.

**Comment by ElishaAz** [comment]
Sayboard is no on F-Droid! https://f-droid.org/en/packages/com.elishaazaria.sayboard/
