### ISSUE TITLE
Can you add a key for Chinese punctuation marks on the keyboard panel

### ISSUE THREAD

**Issue by dsssok** [ElishaAz/Sayboard#23]
![Screenshot_20230331-002226~2](https://user-images.githubusercontent.com/125676564/228903437-731e7de2-d447-447a-9a68-e7bc2cb10cd1.png)
This would make it more convenient to input Chinese punctuation marks.

**Comment by dsssok** [comment]
![InShot_20230331_005431701](https://user-images.githubusercontent.com/125676564/228909752-12feeef8-ae02-4d77-afde-0911dc42326e.gif)
Clicking voice input on other keyboards can switch to the voice panel, so I personally think that adding numbers and letters is not very useful.  But for Chinese, adding punctuation marks is a must.

**Comment by dsssok** [comment]
![20230331_012119](https://user-images.githubusercontent.com/125676564/228915973-5f38fc12-4a89-42db-9cf3-025231ffd382.gif)
Clicking voice input on other keyboards can switch to the voice panel, so I personally think that adding numbers and letters is not very useful.  But for Chinese, adding punctuation marks is a must.

**Comment by ElishaAz** [comment]
Closed by 46ae8bf . You can now configure custom buttons for punctuation
