### ISSUE TITLE
A space character is typed before every word

### ISSUE THREAD

**Issue by dvdmle** [ElishaAz/Sayboard#28]
Currently, whenever a word is dictated, a space is placed before it regardless of whether it is the beginning of a line or of text entry or anything like that. A leading space should only be placed if the utterance is following a letter character or *appropriate* punctuation mark (i.e. yes after commas and periods, no after quotes and asterisks).

Now, ideally, I would also like the option to disable spacing altogether to allow for dictating things like '.com', '.txt', 'whattheheck', etc. The board could have a button for something like that, but I do acknowledge that such a feature could start to complicate things.

**Comment by ElishaAz** [comment]
I finally found the bug.

Closed by 10b5b963dbce4810ab22f6fde526ce5ed19d87f9
