### ISSUE TITLE
Theme interface broken

### ISSUE THREAD

**Issue by S7venLights** [ElishaAz/Sayboard#3]
The theme menu of the app just has the word theme in small orange text on it, no visible buttons  when the actual keyboard  isn't white and green  no dark  mode

**Comment by ThatOneCalculator** [comment]
Yep, can reproduce.

**Comment by ElishaAz** [comment]
Yes, it's just a placehoder right now

**Comment by ElishaAz** [comment]
I implemented it now: c3f08ede87c4fe1935da6c3dfe6188eb7b2f8c1e
