### ISSUE TITLE
[Bug] Vosk model download Error

### ISSUE THREAD

**Issue by CS1o** [ElishaAz/Sayboard#31]
After updating from 2.1 to 4.0 I had to redownload the Vosk language model. That didn't worked. It always errors out. And it says "Error downloading Model" in the Notification bar and "Status: Error" in the APP.
Cleared Cache and Data and reinstalled the APP, switched Networks. Nothing helped.
Installed 2.1 again and downloading the same vosk model instantly works.

Device:
Pixel 7
Android 13
Graphene OS

Also thanks for this APP. Its currently the only way to get a foss STT working with the Openboard fork from Helium.

**Comment by Metr0pl3x** [comment]
Can confirm this issue, shame the downloaded models don't persist between updates.

**Comment by machiav3lli** [comment]
A hack for now is to download the models manually (e.g. from browser) and unzip them into the external data folder of the app (/Android/data/com.elishaazaria.sayboard/files/Models/). NOTE: Root required.

**Comment by ElishaAz** [comment]
I was not able to reproduce this issue myself. Can you please include your device information and logcat if possible?

Here is the (unofficial) version 2.0.2, with most of the logic changes, but not the UI or downloader: [Sayboard-v2.0.2.zip](https://github.com/ElishaAz/Sayboard/files/12847026/Sayboard-v2.0.2.zip). Models should persist if you download them with this version and then update.

As @machiav3lli mentioned, the models can be manually unzipped into /Android/data/com.elishaazaria.sayboard/files/Models/. This can be done with root, but can also be done from a computer with the phone connected for file transfer.

**Comment by CS1o** [comment]
Hey thanks for the Reply.

I updated to that 2.0.2 version and had to redwnload the vosk model. This failed exactly like in 4.0
I deleted the cache and the APP data, uninstalled it and installed it again. Same error after downloading the vosk model.
As the cache fills up i think it isn't a download error, more like an unpack or apply error.

**Comment by ElishaAz** [comment]
I've made some changes in [v4.0.1](https://github.com/ElishaAz/Sayboard/releases/tag/v4.0.1) that might have fixed this issue. Can you please update and tell me if they did?

**Comment by machiav3lli** [comment]
Seems to work fine now

**Comment by CS1o** [comment]
Can confirm it works now. Thanks!
