### ISSUE TITLE
 feature request punctuation  buttons

### ISSUE THREAD

**Issue by S7venLights** [ElishaAz/Sayboard#4]
Basic punctuation buttons, capitilise after fullstops would be good and keyboard height could be smaller, also a key to delete whole words would be nice

**Comment by S7venLights** [comment]
This keyboard has punctuation
https://github.com/Felicis/vosk-android-demo

**Comment by ElishaAz** [comment]
I added an option to set the keyboard height

**Comment by ElishaAz** [comment]
What punctuation keys do you think should be in the keyboard?
And where would you prefer that they will be in the UI?

**Comment by S7venLights** [comment]
Heya 👋 

, 
. 
! 
? 
"
@
#
/
: 
'
&
*
-
+
=
x
÷

Financial sun menu
$
¥
€
₹
R
etc 

%
() 
[ ]
<>
… 
_
♡
~
; 

Basic navigation keys: 
left right up down

**Comment by ElishaAz** [comment]
Sorry I haven't gotten back to you earlier.
This keyboard is supposed to be a companion voice IME to other keyboards like Florisboard or AOSP keyboard. Whenever you need any of these punctuation buttons, you should switch back to the main keyboard using the back button on the top left.

I think I will add a few buttons, perhaps only period and comma, and then use #18 or #14.

**Comment by S7venLights** [comment]
No stress. Yeah I realise I could do that, but using https://github.com/Felicis/vosk-android-demo
which has punctuation
I find much more convenient, being able to add it as I go without needing to switch back.

**Comment by hirntot** [comment]
> you should switch back to the main keyboard using the back button on the top left.

Well, but on the other keyboard, (e. g. Florisboard) there's no "back to IME"-button and therefore this is not very practical. 
On the other hand, you got that far already. If you'd just fork florisboard and add a microphone on/off-switch in the keyboard (and some IME-settings in the settings menu) everything would be perfect!

**Comment by S7venLights** [comment]
Also I don't use Florisboard as I'm pretty happy with multiling O 
:)

**Comment by S7venLights** [comment]
🙌

**Comment by LuccoJ** [comment]
> I think I will add a few buttons, perhaps only period and comma, and then use #18 or #14.

I know you've already added more than those, but I just want to stress my support for more buttons than just period and comma, as it's *really* messy to keep switching back and forth between Sayboard and a regular keyboard for the punctuation that is normally had in a standard sentence. So not all of the buttons that have been proposed, but more punctuation than period and comma... basically, what you already added! This comment is mainly meant as reinforcement for the decisions made so far (including it being configurable). Want to add a semicolon, which is so unduly detested? :wink:

**Comment by S7venLights** [comment]
![Sayboard](https://github.com/ElishaAz/Sayboard/assets/109830095/97d1a729-5ee7-4eea-a2cd-493a6f4f524a)

As you can tell my dream is to have a full qwerty keyboard where I can use speak input too without switching... This is as close as I could get... Haha

**Comment by Charles7z** [comment]
@S7venLights 
I'm in agreement, i want to see a full keyboard while i'm using my voice input so i can switch between the different types of keyboards to enter numbers, punctuation, and even words for corrections or odd words that you know will never be recognized, in my opinion that's the only way to go in the long run, unfortunately the big companies are trying to use AI so that it does everything for the user but it always fails IMO, and makes it so i don't want to use voice input.

So for now i've just made a number and punctuation keyboard.

![sayboard layout](https://github.com/ElishaAz/Sayboard/assets/103839039/5ef8c5c8-ae45-4f2c-a63d-35db0e6a24b4)
