### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [ElishaAz/Sayboard#43]
It's not reproducible. 
[diff.zip](https://github.com/ElishaAz/Sayboard/files/13247857/diff.zip)

Is the apk built from the same commit?

**Comment by ElishaAz** [comment]
> Is the apk built from the same commit?

Yes

I did a new clean build, the APKs show small differences when analyzing. I uploaded the new ones

**Comment by linsui** [comment]
Looks like it's fixed. Thanks!
