### ISSUE TITLE
After 4.1 latest, the backspace (left delete) key doesnt seem to work as expected

### ISSUE THREAD

**Issue by stilez** [ElishaAz/Sayboard#45]
Updated to 4.1 latest release on Github.

started talking. Typed some punctuation. Tried backspace (upper right) and it wouldn't delete left. Experimented.  Couldn't get it to delete left the dictated text (without extra punctuation) either.  Can this be checked? Reproducible?

**Comment by ElishaAz** [comment]
You're right, I don't know how I missed that. In the meantime, you can tap and drag left from the backspace key to delete multiple characters

**Comment by ElishaAz** [comment]
Closed by eb19e0b00578851e0a4dae7d322575341e12e4c0

**Comment by radicalrusty** [comment]
> You're right, I don't know how I missed that. In the meantime, you can tap and drag left from the backspace key to delete multiple characters

The swipe delete works good, I didn't know that part was still operational. Definitely helps.
