### ISSUE TITLE
Capitals

### ISSUE THREAD

**Issue by Vetgans** [ElishaAz/Sayboard#47]
The addition to add punctuation manually is very much appreciated.

It would be even more useful, at least in my opinion, if there would be the possibility to automatically continue with a capital after using a period, question or exclamation mark, or using the enter button.

**Comment by MXC48** [comment]
yes, and it would be nice if the capital letter at the beginning of a sentence was automatically added, which would mean fewer changes after the fact.

**Comment by Vetgans** [comment]
Wow, already implemented.
Thanks for all the effort!
