### ISSUE TITLE
Crash by using german model

### ISSUE THREAD

**Issue by sandoxy** [ElishaAz/Sayboard#5]
Thank you for the great app!!! I`ve been searching for this app for years:)

I downloaded the german voice model. When I choose it, the Sayboard crashes.

**Comment by ElishaAz** [comment]
Thank you for your contribution.
Have you tried other models?
All m2 dels are downloaded from https://alphacephei.com/vosk/models . Are you able to download the german model form there in your browser?

**Comment by sandoxy** [comment]
Other models work correctly. Maybe it occures, because all models in this app are "small" and gernan is not?

**Comment by ElishaAz** [comment]
You're right. I put the big model by mistake instead of the small one. The keyboard works with the small model.

**Comment by sandoxy** [comment]
Is there a way, that I get the small german model? Is there a folder, where I could download the small model to? Or should I wait until the next update.

**Comment by ElishaAz** [comment]
The models are saved in the application's private storage location (/data/user/0/com.elishaazaria.sayboard/files/Models) so you can't access them without root.

Here is the new release: https://github.com/ElishaAz/Sayboard/releases/tag/v2.0.1
