### ISSUE TITLE
Enter key and backspace key

### ISSUE THREAD

**Issue by radicalrusty** [ElishaAz/Sayboard#50]
Hi, first off let me just say how awesome it is that Sayboard can simultaneously input voice to text as well as manually typed out keyboard symbols (just the few punctuation keys on each side are awesome and almost all I'd ever need). I've been asking about this feature for YEARS since voice to text first became a thing, it's great to see it implemented here.

Secondly, I don't know if it's a bug or maybe something that just hasn't been fully implemented yet but trying to use the enter key or the backspace key while sayboard is pulled up does nothing. Is this a known issue or has anyone else had this problem?

If both of those keys could be fixed, it would be super helpful for text editing while voice dictating.

Thanks for this awesome app, I've been trying to de-google and de-corporate lately and this is one of the things that has really helped me keep a normal routine otherwise.

**Comment by ElishaAz** [comment]
The backspace key is a known issue (see #45), and will be fixed in the next release.

**Comment by ElishaAz** [comment]
The enter key should be fixed in the next release
