### ISSUE TITLE
Register as a SpeechRecognizer

### ISSUE THREAD

**Issue by ElishaAz** [ElishaAz/Sayboard#54]

**Comment by Reed-Schimmel** [comment]
I would also like this to be selectable in `Settings -> System -> Languages -> Voice input`

![Screenshot_20231207-173508](https://github.com/ElishaAz/Sayboard/assets/3477188/5c0bfea3-2b31-44d1-9b22-cd133e2f498d)

**Comment by ElishaAz** [comment]
I didn't know that existed. Do you know of any app that shows up as an option there?

**Comment by MXC48** [comment]
> I didn't know that existed. Do you know of any app that shows up as an option there?

![Screenshot_20231212-193449_Paramètres.png](https://github.com/ElishaAz/Sayboard/assets/123580315/1eddd98e-ba14-4595-8071-a517abbc0603)

for the moment I know Google voice input

**Comment by inguna87** [comment]
Please can you implement this feature? This is what I have on my device
![Screenshot_20231231-153046](https://github.com/ElishaAz/Sayboard/assets/103364968/f7cc45b5-9633-403b-932c-04dc5b0f7caa)

**Comment by ElishaAz** [comment]
> I would also like this to be selectable in Settings -> System -> Languages -> Voice input

Looking at it again, that just seems to be the new place to choose the default SpeechRecognizer (it used to be under Settings -> Apps -> Default Apps -> Home assistant -> Voice input)

Which means that this issue is precisely about that

**Comment by dp0s** [comment]
I just installed the latest update of Sayboard and it is available as Voice Input Method now. That means I can also use it within any Termux script running in the background :)

Thanks a lot!
