### ISSUE TITLE
Sayboard does not show microphone icon and does not seek audio input

### ISSUE THREAD

**Issue by compilebunny** [ElishaAz/Sayboard#62]
Android 10
Sayboard 4.1.1 from fdroid

Sayboard does not show the microphone icon when activated and therefore has no way of starting to record.

![nomic](https://github.com/ElishaAz/Sayboard/assets/78088807/403fb10c-b092-4126-9f0a-f0a3b251e216)

Sayboard has been assigned microphone access in the system settings.

**Comment by ElishaAz** [comment]
I'm sorry to hear that.

Did you install a language model in the app?

**Comment by compilebunny** [comment]
The English (United States) model is installed.. 

Increasing the keyboard height worked to display the icon. After that, the keyboard works. Thanks.

**Comment by ElishaAz** [comment]
You're welcome. If the issue it's solved, please close it.
