### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [ElishaAz/Sayboard#63]
[diff.html.zip](https://github.com/ElishaAz/Sayboard/files/14156806/diff.html.zip)

Is the build environment changed? Maybe a different ndk is used? Could you please take a look? Thanks!

**Comment by ElishaAz** [comment]
I've deleted all the ndk versions other than the one in the [fdroid data repo](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.elishaazaria.sayboard.yml?ref_type=heads), and changed my default JDK to match as well, and there is a 10kb difference in libjnidispatch.so.

I've re-uploaded the release.

**Comment by linsui** [comment]
Thanks!
