### ISSUE TITLE
delete button looks the same as going back

### ISSUE THREAD

**Issue by e075e** [ElishaAz/Sayboard#66]
On sayboard input page, the "delete" button looks the same as "going back" button.

It will be nice to make it different.

If it comes from an image, openboard (open source) has these

https://github.com/openboard-team/openboard/blob/master/app/src/main/res/drawable-hdpi/sym_keyboard_delete_lxx_light.png

https://github.com/openboard-team/openboard/blob/master/app/src/main/res/drawable-hdpi/sym_keyboard_delete_lxx_dark.png

**Comment by ElishaAz** [comment]
Fixed by 85517c4140be72f7f506b6342b33275b2f41215f
