### ISSUE TITLE
UI is missing a selected language indicator

### ISSUE THREAD

**Issue by Janghou** [ElishaAz/Sayboard#77]
Sayboard is working fine here on LineageOS, with multi-language support by pressing the language change (Globe) button.

What I'm missing though is a language indicator for which language is selected. On the default AOSP keyboard this is shown (in dimmed letters) on the spacebar.

**Comment by ElishaAz** [comment]
Duplicate of #70 and#72 . This is already solved, I just hadn't created a new relase yet

**Comment by Janghou** [comment]
OK, thx, waiting for the new release.
