### ISSUE TITLE
Feature Request: Have Sayboard always listening in the *background*, and typing even when the on-screen keyboard isn't showing

### ISSUE THREAD

**Issue by Software27425** [ElishaAz/Sayboard#84]
To explain my dictation need, let me give a bit of background on how I work:

I use an Android productivity app on my primary phone that accepts many keyboard shortcuts to perform actions, but I prefer to dictate my actions rather than use a physical keyboard.

So I install a Bluetooth keyboard app on a secondary phone, with Sayboard as the input on the secondary phone. When I dictate, the text input gets sent from the secondary phone to the primary phone, and then on the primary, an automation app converts the text into the keyboard shortcut, performing my desired action.

My desire is to have Sayboard always running in the background of my primary phone, and converting dictations into text input with the help of WRITE_SECURE_SETTINGS ADB permissions. This way, I would have no need to have two Android phones. 

This can technically be done with the automation app Tasker and its voice plugin AutoVoice (which can run in the background regardless of what you're doing) : it can convert designated dictations into text input. My problem with the AutoVoice plugin is that its speech recognition is way too slow to be practical for me.

This is where the Vosk engine comes in. I love Sayboard's speech, and it would be great to have its speech recognition always on so that's it's typing even when an on-screen keyboard isn't showing.

**Comment by ElishaAz** [comment]
This seems a little out-of-scope for this app. Perhaps you can try asking AutoVoice to support the SpeechRecognizer API, which will let you use Sayboard as the speech-to-text backend
